"""
Database models for Kosmos AI Scientist.

Models:
- Experiment: Research experiments
- Hypothesis: Generated hypotheses
- Result: Experiment results
- Paper: Literature papers
- Agent: Agent instances
"""

from sqlalchemy import Column, String, Integer, Float, Boolean, Text, DateTime, ForeignKey, JSON, Enum as SQLEnum
from sqlalchemy.types import TypeDecorator
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
import enum


class UTCDateTime(TypeDecorator):
    """DateTime that always returns tz-aware UTC values.

    SQLite does not persist tzinfo, so a value written as
    ``datetime.now(timezone.utc)`` (aware) comes back naive — which then blows up
    any ``datetime.now(timezone.utc) - <row>.created_at`` subtraction with
    "can't subtract offset-naive and offset-aware datetimes". This decorator
    normalizes to naive-UTC on write and reattaches UTC tzinfo on read so all
    timestamps stay aware and comparable across the codebase.
    """

    impl = DateTime
    cache_ok = True

    def process_bind_param(self, value, dialect):
        if value is not None and value.tzinfo is not None:
            value = value.astimezone(timezone.utc).replace(tzinfo=None)
        return value

    def process_result_value(self, value, dialect):
        if value is not None and value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value


Base = declarative_base()


class ExperimentStatus(str, enum.Enum):
    """Experiment status."""
    CREATED = "created"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class HypothesisStatus(str, enum.Enum):
    """Hypothesis status."""
    GENERATED = "generated"
    TESTING = "testing"
    SUPPORTED = "supported"
    REJECTED = "rejected"
    INCONCLUSIVE = "inconclusive"


class Experiment(Base):
    """
    Experiment model.

    Represents a research experiment designed to test a hypothesis.
    """
    __tablename__ = "experiments"

    id = Column(String, primary_key=True)
    hypothesis_id = Column(String, ForeignKey("hypotheses.id"), nullable=False)
    experiment_type = Column(String, nullable=False)  # computational, data_analysis, simulation
    description = Column(Text, nullable=False)
    protocol = Column(JSON, nullable=False)  # Experiment protocol details

    status = Column(SQLEnum(ExperimentStatus), default=ExperimentStatus.CREATED)
    domain = Column(String, nullable=False)  # biology, physics, etc.

    # Execution details
    code_generated = Column(Text, nullable=True)
    execution_time_seconds = Column(Float, nullable=True)
    error_message = Column(Text, nullable=True)

    # Timestamps
    created_at = Column(UTCDateTime, default=lambda: datetime.now(timezone.utc))
    started_at = Column(UTCDateTime, nullable=True)
    completed_at = Column(UTCDateTime, nullable=True)

    # Relationships
    hypothesis = relationship("Hypothesis", back_populates="experiments")
    results = relationship("Result", back_populates="experiment", cascade="all, delete-orphan")

    def to_dict(self) -> dict:
        """Serialize to a plain dict for reporting/JSON export.

        Includes 'type' and 'duration_seconds' aliases expected by the results
        viewer/markdown exporter (which otherwise crashed on raw ORM objects).
        """
        return {
            "id": self.id,
            "hypothesis_id": self.hypothesis_id,
            "experiment_type": self.experiment_type,
            "type": self.experiment_type,  # alias for results viewer / markdown export
            "description": self.description,
            "protocol": self.protocol,
            "status": self.status.value if self.status is not None else "pending",
            "domain": self.domain,
            # Default to 0.0 (not None) so format_duration()/numeric formatting is safe.
            "execution_time_seconds": self.execution_time_seconds if self.execution_time_seconds is not None else 0.0,
            "duration_seconds": self.execution_time_seconds if self.execution_time_seconds is not None else 0.0,  # alias for markdown export
            "error_message": self.error_message,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
        }

    def __repr__(self):
        return f"<Experiment {self.id} status={self.status}>"


class Hypothesis(Base):
    """
    Hypothesis model.

    Represents a scientific hypothesis generated by the system.
    """
    __tablename__ = "hypotheses"

    id = Column(String, primary_key=True)
    research_question = Column(Text, nullable=False)
    statement = Column(Text, nullable=False)
    rationale = Column(Text, nullable=False)

    domain = Column(String, nullable=False)
    status = Column(SQLEnum(HypothesisStatus), default=HypothesisStatus.GENERATED)

    # Scoring
    novelty_score = Column(Float, nullable=True)
    testability_score = Column(Float, nullable=True)
    confidence_score = Column(Float, nullable=True)

    # Literature context
    related_papers = Column(JSON, nullable=True)  # List of paper IDs

    # Timestamps
    created_at = Column(UTCDateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(UTCDateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    # Relationships
    experiments = relationship("Experiment", back_populates="hypothesis")

    def to_dict(self) -> dict:
        """Serialize to a plain dict for reporting/JSON export.

        Includes a 'claim' alias (mapped from 'statement') expected by the results
        viewer/markdown exporter (which otherwise crashed on raw ORM objects).
        """
        return {
            "id": self.id,
            "research_question": self.research_question,
            "statement": self.statement,
            "claim": self.statement,  # alias for results viewer / markdown export
            "rationale": self.rationale,
            "domain": self.domain,
            "status": self.status.value if self.status is not None else "pending",
            # Numeric scores default to 0.0 (not None) so downstream :.2f/metric
            # formatting in the results viewer/exporter never chokes on None.
            "novelty_score": self.novelty_score if self.novelty_score is not None else 0.0,
            "testability_score": self.testability_score if self.testability_score is not None else 0.0,
            "confidence_score": self.confidence_score if self.confidence_score is not None else 0.0,
            "priority_score": self.confidence_score if self.confidence_score is not None else 0.0,
            "related_papers": self.related_papers,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }

    def __repr__(self):
        return f"<Hypothesis {self.id} status={self.status}>"


class Result(Base):
    """
    Result model.

    Stores experimental results and analysis.
    """
    __tablename__ = "results"

    id = Column(String, primary_key=True)
    experiment_id = Column(String, ForeignKey("experiments.id"), nullable=False)

    # Raw results
    data = Column(JSON, nullable=False)  # Result data
    statistical_tests = Column(JSON, nullable=True)  # Statistical test results

    # Analysis
    interpretation = Column(Text, nullable=True)  # Claude's interpretation
    key_findings = Column(JSON, nullable=True)  # List of key findings
    supports_hypothesis = Column(Boolean, nullable=True)

    # Significance
    p_value = Column(Float, nullable=True)
    effect_size = Column(Float, nullable=True)
    confidence_interval = Column(JSON, nullable=True)

    # Visualization
    figures = Column(JSON, nullable=True)  # Paths to generated figures

    # Timestamps
    created_at = Column(UTCDateTime, default=lambda: datetime.now(timezone.utc))

    # Relationships
    experiment = relationship("Experiment", back_populates="results")

    def __repr__(self):
        return f"<Result {self.id} experiment={self.experiment_id}>"


class Paper(Base):
    """
    Paper model.

    Represents scientific literature papers.
    """
    __tablename__ = "papers"

    id = Column(String, primary_key=True)  # arXiv ID, DOI, etc.
    title = Column(String, nullable=False)
    authors = Column(JSON, nullable=False)  # List of author names
    abstract = Column(Text, nullable=False)

    # Source
    source = Column(String, nullable=False)  # arXiv, semantic scholar, pubmed
    url = Column(String, nullable=True)
    doi = Column(String, nullable=True)
    arxiv_id = Column(String, nullable=True)

    # Metadata
    publication_date = Column(UTCDateTime, nullable=True)
    domain = Column(String, nullable=True)
    keywords = Column(JSON, nullable=True)

    # Analysis
    summary = Column(Text, nullable=True)  # AI-generated summary
    key_methods = Column(JSON, nullable=True)
    key_findings = Column(JSON, nullable=True)
    relevance_score = Column(Float, nullable=True)

    # Embeddings (for semantic search)
    embedding = Column(JSON, nullable=True)  # Vector embedding

    # Timestamps
    created_at = Column(UTCDateTime, default=lambda: datetime.now(timezone.utc))
    analyzed_at = Column(UTCDateTime, nullable=True)

    def __repr__(self):
        return f"<Paper {self.id}: {self.title[:50]}>"


class AgentRecord(Base):
    """
    Agent record model.

    Tracks agent instances and their state.
    """
    __tablename__ = "agents"

    id = Column(String, primary_key=True)
    agent_type = Column(String, nullable=False)
    status = Column(String, nullable=False)

    # Configuration
    config = Column(JSON, nullable=True)

    # State
    state_data = Column(JSON, nullable=True)

    # Statistics
    messages_sent = Column(Integer, default=0)
    messages_received = Column(Integer, default=0)
    tasks_completed = Column(Integer, default=0)
    errors_encountered = Column(Integer, default=0)

    # Timestamps
    created_at = Column(UTCDateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(UTCDateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))
    stopped_at = Column(UTCDateTime, nullable=True)

    def __repr__(self):
        return f"<Agent {self.agent_type} {self.id}>"


class ResearchSession(Base):
    """
    Research session model.

    Groups related experiments under a research session.
    """
    __tablename__ = "research_sessions"

    id = Column(String, primary_key=True)
    research_question = Column(Text, nullable=False)
    domain = Column(String, nullable=False)

    # Status
    status = Column(String, default="active")  # active, paused, completed
    iteration = Column(Integer, default=1)

    # Progress
    hypotheses_generated = Column(Integer, default=0)
    experiments_completed = Column(Integer, default=0)
    discoveries_made = Column(JSON, nullable=True)

    # Configuration
    max_iterations = Column(Integer, default=10)
    autonomous_mode = Column(Boolean, default=True)

    # Timestamps
    created_at = Column(UTCDateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(UTCDateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))
    completed_at = Column(UTCDateTime, nullable=True)

    def __repr__(self):
        return f"<ResearchSession {self.id} iteration={self.iteration}>"
